// GENERATED by :seedTool from the dev Firestore project (nonogram-ba791): every approved
// puzzle, as of the last run. Do not edit by hand — run `./gradlew :seedTool:run` and
// commit the result. See docs/seeding.md.
package com.trainpaths.nonogram.cache

/**
 * One built-in puzzle, inserted by `AppSDK.seedIfEmpty`.
 *
 * [id] is the dev `nonograms/{id}` document id this came from, not a fresh number: the seeds
 * must land on the same id on every device, or progress synced from one would attach to a
 * different puzzle on the next. It sits in the same `[2^20, 2^53)` space every puzzle id is
 * minted from, so it is unique for the same reason theirs are.
 */
internal class SeedPuzzle(
    val id: Long,
    val name: String?,
    val difficulty: String,
    val solution: List<List<Int>>,
)

internal val SEED_PUZZLES: List<SeedPuzzle> = listOf(
    SeedPuzzle(
        id = 5981082931731213L,
        name = "Ritters",
        difficulty = "EASY",
        solution = listOf(
            listOf(1, 1, 1, 1, 1),
            listOf(1, 0, 0, 0, 1),
            listOf(0, 0, 0, 0, 1),
            listOf(1, 0, 0, 0, 1),
            listOf(1, 1, 1, 1, 1),
        ),
    ),
    SeedPuzzle(
        id = 6964793539260140L,
        name = "asdf",
        difficulty = "EASY",
        solution = listOf(
            listOf(0, 1, 1, 1, 0),
            listOf(0, 1, 1, 1, 0),
            listOf(0, 1, 1, 1, 0),
            listOf(0, 1, 1, 1, 0),
            listOf(0, 1, 1, 1, 0),
        ),
    ),
)
