package com.trainpaths.nonogram.seed

/** A puzzle as it will be written into `SeedPuzzles.kt`. */
internal data class Seed(
    val id: Long,
    val name: String?,
    val difficulty: String,
    val solution: List<List<Int>>,
)

/** The whole file — the exporter never reads it back, it just rewrites it from dev. */
internal fun renderSeedFile(seeds: List<Seed>, projectId: String): String =
    buildString {
        appendLine("// GENERATED by :seedTool from the dev Firestore project ($projectId): every approved")
        appendLine("// puzzle, as of the last run. Do not edit by hand — run `./gradlew :seedTool:run` and")
        appendLine("// commit the result. See docs/seeding.md.")
        appendLine("package com.trainpaths.nonogram.cache")
        appendLine()
        appendLine("/**")
        appendLine(" * One built-in puzzle, inserted by `AppSDK.seedIfEmpty`.")
        appendLine(" *")
        appendLine(" * [id] is the dev `nonograms/{id}` document id this came from, not a fresh number: the seeds")
        appendLine(" * must land on the same id on every device, or progress synced from one would attach to a")
        appendLine(" * different puzzle on the next. It sits in the same `[2^20, 2^53)` space every puzzle id is")
        appendLine(" * minted from, so it is unique for the same reason theirs are.")
        appendLine(" */")
        appendLine("internal class SeedPuzzle(")
        appendLine("    val id: Long,")
        appendLine("    val name: String?,")
        appendLine("    val difficulty: String,")
        appendLine("    val solution: List<List<Int>>,")
        appendLine(")")
        appendLine()
        appendLine("internal val SEED_PUZZLES: List<SeedPuzzle> = listOf(")
        seeds.forEach { seed ->
            appendLine("    SeedPuzzle(")
            appendLine("        id = ${seed.id}L,")
            appendLine("        name = ${seed.name?.let { "\"${it.escaped()}\"" } ?: "null"},")
            appendLine("        difficulty = \"${seed.difficulty}\",")
            appendLine("        solution = listOf(")
            seed.solution.forEach { row -> appendLine("            listOf(${row.joinToString(", ")}),") }
            appendLine("        ),")
            appendLine("    ),")
        }
        appendLine(")")
    }

private fun String.escaped() = replace("\\", "\\\\").replace("\"", "\\\"").replace("$", "\${'$'}")
